---
title: Backends for R-DBI
comments: false
margin-header: "MIT License"
format:
  html:
    from: markdown+emoji
    page-layout: full
open-graph:
  description: "Backends for R-DBI."
twitter-card:
  description: "Backends for R-DBI."
---
---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

Do you maintain a backend and think that yours should be on this list?
Please open an issue in the [backends repository](https://github.com/r-dbi/backends).

```{r all-from-file, include = FALSE}
all_df <- jsonlite::fromJSON("https://r-dbi.github.io/backends/all.json", flatten = TRUE)
```

```{r all-url, echo = FALSE, results='asis'}
format_pkg <- function(name, version, title, description, date, maintainer, license, url, bugs) {

  if (is.na(date)) {
    date <- ""
  } else {
    date <- paste0(" (", date, ")")
  }

  if (length(url) > 0 && !anyNA(url)) {
    name <- paste0("[", name, "](", url[[1]], ")")
    url <- url[-1]
  }
  
  if (length(url) > 0 && !anyNA(url)) {
    url <- paste0(" [:link:](", url, ")", collapse = "")
  } else {
    url <- ""
  }
  
  if (!is.na(bugs)) {
    bugs <- paste0(" [:bug:](", bugs, ")")
  } else {
    bugs <- ""
  }
  
  paste0(
    "## ", name, " ", version, date, url, bugs, "\n\n",
    
    title, "\n\n",
    
    description, "\n\n",
    
    "Maintainer: ", maintainer, ". License: ", license, "\n\n"
  )
}

cat(purrr::pmap_chr(all_df, format_pkg) |> paste(collapse = "\n\n"))
```
